on:
  push:
    branches:
        -main
   

jobs:
  build_docker:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            if [ "${{ github.event_name }}" != "push" ] || [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "Skipping Docker image build and push for branch ${GITHUB_REF}"
            exit 0
            fi
            
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          
            rev=$(git rev-parse --short HEAD)
            docker build . -t hello
            
            docker tag hello 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidatnr-2007:$rev
            docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidatnr-2007:$rev
            docker tag hello 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidatnr-2007:latest
            docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidatnr-2007:latest